---
- name: Ansible apt module examples
  hosts: all
  become: true

  tasks:
    - name: APT update
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: yes
      when: 
        ansible_distribution == "Ubuntu"

    - name: DNF update
      dnf:
        name: "*"
        state: latest
      when: 
        ansible_distribution == "Fedora"

    - name: Zypper update
      community.general.zypper:
        name: '*'
        state: latest
      when: 
        ansible_distribution == "openSUSE Leap"